gui:
  -
    title: "边框"
    itemtype: WHITE_STAINED_GLASS_PANE
    itemon: '1'
  -
    title: "单人匹配"
    lore:
      - "起床战争"
      - "人数%joinedPlayer%/%gameMaxPlayer%"
    gameid: bedwar
    itemtype: BLACK_BED
    itemon: '2'
  -
    title: "单人匹配"
    lore:
      - "老汉推车"
      - "人数%s/%s"
    gameid: pushcar
    itemtype: CHEST_MINECART
    itemon: '3'
lobbyscore:
  title: "个人匹配信息"
  lore:
    - "match equit 退出匹配"
    - "胜: %wins%"
    - "败: %losers%"
    - "胜率: %winrate%"
    - "排名: %rank%"
#竞技场
pools:
  -
    title: '竞技场名'
    type: 'bedwar' #竞技场类型
    max-player: 20 #最多匹配人数
    min-player: 2  #最少匹配人数
    timeout: 60
    varify-time: 10


