games:
  -
    name: "起床战争"
    minPlayer: 2 #最小人数
    maxPlayer: 16 #最大人数
    gameId: "bedwar" #匹配游戏的id
    timeout: 20 #等待x秒之后进行最低条件的匹配
    varifyTime: 10 #匹配开始之前的确认时间
    bar: #顶部进度条
      WARTING: "在等待匹配期间，并不会影响您正常游戏哦!"
      BEFORESTART: "匹配还有%s秒即将开始，请做好准备!"
      START: "匹配已经开始！"
      ENDING:
    board: #计分板
      WARTING: #等待状态
        title: "个人匹配信息"
        lore:
          - "match equit 退出匹配"
          - "胜: %wins%"
          - "败: %losers%"
          - "胜率: %winrate%"
          - "排名: %rank%"
      BEFORESTART:
      START:
      ENDING:
